/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package flightbookingsystem;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

/**
 *
 * @author BiiBii
 */
public class FlightBookingSystem extends javax.swing.JFrame {

    /**
     * Creates new form FlightBookingSystem
     */
    public FlightBookingSystem() {
        initComponents();
        jOneWayButton.setVisible(false);
        jRoundTripButton.setVisible(false);
        jReturnTextField.setVisible(false);
        jReturnButton.setVisible(false);
        jDepartTextField.setVisible(false);
        jDepartButton.setVisible(false);
        jAdultComboBox.setVisible(false);
        jKidComboBox.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDepartTextField = new javax.swing.JTextField();
        jDepartButton = new javax.swing.JButton();
        jReturnTextField = new javax.swing.JTextField();
        jReturnButton = new javax.swing.JButton();
        jRoundTripButton = new javax.swing.JRadioButton();
        jOneWayButton = new javax.swing.JRadioButton();
        jAdultComboBox = new javax.swing.JComboBox();
        jKidComboBox = new javax.swing.JComboBox();
        jBookingButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        bookingFlightMenu = new javax.swing.JMenu();
        cancelFlightMenu = new javax.swing.JMenu();
        searchMenu = new javax.swing.JMenu();
        myAccountMenu = new javax.swing.JMenu();
        logoutMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Flight Booking System");
        setAutoRequestFocus(false);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jDepartTextField.setText("DEPART");
        jDepartTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDepartTextFieldActionPerformed(evt);
            }
        });

        jDepartButton.setText("DEPART");
        jDepartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDepartButtonActionPerformed(evt);
            }
        });

        jReturnTextField.setText("RETURN");

        jReturnButton.setText("RETURN");
        jReturnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jReturnButtonActionPerformed(evt);
            }
        });

        jRoundTripButton.setText("Round Trip");
        jRoundTripButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRoundTripButtonActionPerformed(evt);
            }
        });

        jOneWayButton.setText("One Way");
        jOneWayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOneWayButtonActionPerformed(evt);
            }
        });

        jAdultComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0 Adults", "1 Adult", "2 Adults" }));
        jAdultComboBox.setSelectedIndex(1);

        jKidComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0 Kids", "1 Kid", "2 Kids" }));

        jBookingButton.setText("Booking Flight");

        bookingFlightMenu.setText("Booking Flight");
        bookingFlightMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookingFlightMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(bookingFlightMenu);

        cancelFlightMenu.setText("Cancel Flight");
        cancelFlightMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelFlightMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(cancelFlightMenu);

        searchMenu.setText("Search");
        jMenuBar1.add(searchMenu);

        myAccountMenu.setText("My account");
        jMenuBar1.add(myAccountMenu);

        logoutMenu.setText("Logout");
        jMenuBar1.add(logoutMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRoundTripButton)
                                .addGap(67, 67, 67)
                                .addComponent(jOneWayButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jReturnTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jDepartTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jDepartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jReturnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jAdultComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)
                                        .addComponent(jKidComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jBookingButton)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRoundTripButton)
                    .addComponent(jOneWayButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDepartTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDepartButton))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jReturnTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jReturnButton))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jKidComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAdultComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jBookingButton)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jDepartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDepartButtonActionPerformed
        final JFrame f = new JFrame();
        f.getContentPane();
	f.pack();
	jDepartTextField.setText(new DatePicker(f).setPickedDate());
    }//GEN-LAST:event_jDepartButtonActionPerformed

    private void jReturnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jReturnButtonActionPerformed
        final JFrame f = new JFrame();
	f.getContentPane();
	f.pack();
	jReturnTextField.setText(new DatePicker(f).setPickedDate());
    }//GEN-LAST:event_jReturnButtonActionPerformed

    private void jOneWayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOneWayButtonActionPerformed
        jRoundTripButton.setSelected(false);
        jOneWayButton.setSelected(true);
        jReturnTextField.setVisible(false);
        jReturnButton.setVisible(false);
    }//GEN-LAST:event_jOneWayButtonActionPerformed

    private void jRoundTripButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRoundTripButtonActionPerformed
        jRoundTripButton.setSelected(true);
        jOneWayButton.setSelected(false);
        jReturnTextField.setVisible(true);
        jReturnButton.setVisible(true);
    }//GEN-LAST:event_jRoundTripButtonActionPerformed

    private void jDepartTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDepartTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDepartTextFieldActionPerformed

    private void bookingFlightMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookingFlightMenuMouseClicked
        jOneWayButton.setVisible(true);
        jRoundTripButton.setVisible(true);
        jRoundTripButton.setSelected(true);
        jReturnTextField.setVisible(true);
        jReturnButton.setVisible(true);
        jDepartTextField.setVisible(true);
        jDepartButton.setVisible(true);
        jAdultComboBox.setVisible(true);
        jKidComboBox.setVisible(true);
    }//GEN-LAST:event_bookingFlightMenuMouseClicked

    private void cancelFlightMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelFlightMenuMouseClicked
        
        
        jRoundTripButton = new javax.swing.JRadioButton();
        jRoundTripButton.setText("Round Trip");
        jRoundTripButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRoundTripButtonActionPerformed(evt);
            }
        });
        jRoundTripButton.setVisible(true);
    }//GEN-LAST:event_cancelFlightMenuMouseClicked
    
    // class DatePicker
    
    class DatePicker{
        int month = java.util.Calendar.getInstance().get(java.util.Calendar.MONTH);
        int year = java.util.Calendar.getInstance().get(java.util.Calendar.YEAR);
        JLabel l1 = new JLabel("", JLabel.CENTER);
        String day = "";
        JDialog d;
        JButton[] button = new JButton[49];
        
        public DatePicker(JFrame parent){
            d = new JDialog();
            d.setModal(true);
            String[] header = { "Sun", "Mon", "Tue", "Wed", "Thur", "Fri", "Sat" };
            JPanel p1 = new JPanel(new GridLayout(7, 7));
            p1.setPreferredSize(new Dimension(430, 120));
            for (int x = 0; x < button.length; x++) {
                final int selection = x;
		button[x] = new JButton();
		button[x].setFocusPainted(false);
		button[x].setBackground(Color.white);
		if (x > 6)
                    button[x].addActionListener(new ActionListener() {
                        public void actionPerformed(ActionEvent ae) {
                            day = button[selection].getActionCommand();
                            d.dispose();
			}
                    });
		if (x < 7) {
                    button[x].setText(header[x]);
                    button[x].setForeground(Color.red);
		}
                    p1.add(button[x]);
            }
            JPanel p2 =  new JPanel(new GridLayout(1, 3));
            JButton previous = new JButton("<< Previous");
            previous.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent ae) {
                    month--;
                    displayDate();
                }
            });
            p2.add(previous);
            p2.add(l1);
            JButton next = new JButton("Next >>");
            next.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent ae) {
                    month++;
                    displayDate();
                }
            });
            p2.add(next);
            d.add(p1, BorderLayout.CENTER);
            d.add(p2, BorderLayout.SOUTH);
            d.pack();
            d.setLocationRelativeTo(parent);
            displayDate();
            d.setVisible(true);
        }
        
        public void displayDate() {
            for (int x = 7; x < button.length; x++)
                button[x].setText("");
            java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("MMMM yyyy");
            java.util.Calendar cal = java.util.Calendar.getInstance();
            cal.set(year, month, 1);
            int dayOfWeek = cal.get(java.util.Calendar.DAY_OF_WEEK);
            int daysInMonth = cal.getActualMaximum(java.util.Calendar.DAY_OF_MONTH);
            for (int x = 6 + dayOfWeek, day = 1; day <= daysInMonth; x++, day++)
                button[x].setText("" + day);
            l1.setText(sdf.format(cal.getTime()));
            d.setTitle("Date Picker");
        }
        
        public String setPickedDate() {
            if (day.equals(""))
                return day;
            java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd-MM-yyyy");
            java.util.Calendar cal = java.util.Calendar.getInstance();
            cal.set(year, month, Integer.parseInt(day));
            return sdf.format(cal.getTime());
        }
    }
    // End of class DatePicker
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FlightBookingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FlightBookingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FlightBookingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FlightBookingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FlightBookingSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu bookingFlightMenu;
    private javax.swing.JMenu cancelFlightMenu;
    private javax.swing.JComboBox jAdultComboBox;
    private javax.swing.JButton jBookingButton;
    private javax.swing.JButton jDepartButton;
    private javax.swing.JTextField jDepartTextField;
    private javax.swing.JComboBox jKidComboBox;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButton jOneWayButton;
    private javax.swing.JButton jReturnButton;
    private javax.swing.JTextField jReturnTextField;
    private javax.swing.JRadioButton jRoundTripButton;
    private javax.swing.JMenu logoutMenu;
    private javax.swing.JMenu myAccountMenu;
    private javax.swing.JMenu searchMenu;
    // End of variables declaration//GEN-END:variables
}
